# Generated by Django 5.1.6 on 2025-02-24 15:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0003_facture_taux_tva_alter_article_quantite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='taux_tva',
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturations.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
