# Generated by Django 5.1.6 on 2025-03-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0004_remove_facture_taux_tva_alter_article_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='FactureGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturations.client')),
                ('factures', models.ManyToManyField(related_name='factures_globales', to='facturations.facture')),
            ],
        ),
    ]
