# Generated by Django 5.1.6 on 2025-03-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0006_factureglobale_date_emission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureglobale',
            name='date_emission',
        ),
        migrations.AlterField(
            model_name='factureglobale',
            name='factures',
            field=models.ManyToManyField(to='facturations.facture'),
        ),
    ]
