# Generated by Django 5.1.6 on 2025-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0007_remove_factureglobale_date_emission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='est_globale',
            field=models.BooleanField(default=False),
        ),
    ]
