# Generated by Django 5.1.6 on 2025-03-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0008_facture_est_globale'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureglobale',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
