# Generated by Django 5.1.6 on 2025-02-24 07:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0002_facture_arrete_somme_alter_facture_total_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='facturations.client'),
        ),
    ]
