# Generated by Django 5.1.6 on 2025-03-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0005_alter_facture_date_emission_factureglobale'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureglobale',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
