# Generated by Django 5.1.6 on 2025-03-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0009_factureglobale_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureglobale',
            name='numero',
        ),
        migrations.AlterField(
            model_name='factureglobale',
            name='factures',
            field=models.ManyToManyField(related_name='factures_globales', to='facturations.facture'),
        ),
    ]
